# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d typeormnest']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
